---
name: "Pull Request"
description: "submit a pull request"
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: I agree to the [Developer Certificate of Origin](https://developercertificate.org/)
          required: true
        - label: I updated any user-documentation that is impacted by my change.
          required: true
        - label: I tested my changes and ensured existing functionality wasn't broken.
          required: true
        - label: I tested my changes on all the supported platforms (optional).
          required: false
  - type: textarea
    id: description
    attributes:
      label: What does your PR provide?
      placeholder: A clear and concise description of what is being added via the PR.
    validations:
      required: true
