# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REQUIRED_COVERAGE: 0

jobs:
  build:
    name: python checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dev requirements
      run: pip install -r dev-requirements

    - name: Check formatting
      run: python -m black --check .

    - name: Check typing
      run: python -m mypy --config-file pyproject.toml .

    - name: Check pylint
      run: python -m pylint --rcfile pyproject.toml *.py vem

    - name: Execute tests
      run: python -m pytest --cov=vem --cov-fail-under $REQUIRED_COVERAGE
